#pragma once

#include "driver/gpio.h"

// I2C

#define I2C_MASTER_SCL_GPIO GPIO_NUM_1
#define I2C_MASTER_SDA_GPIO GPIO_NUM_2

// TLC5948

#define TLC5948_PIN_MOSI GPIO_NUM_35     // SIN (Serial Data Input)
#define TLC5948_PIN_SCLK GPIO_NUM_36     // SCLK (Serial Clock)
#define TLC5948_PIN_XLAT GPIO_NUM_47     // LAT (Data Latch)
#define TLC5948_PIN_GSCLK GPIO_NUM_48    // GSCLK (Grayscale Clock)

// High side switches

#define HIGH_SIDE_GPIO_00 GPIO_NUM_4
#define HIGH_SIDE_GPIO_01 GPIO_NUM_5
#define HIGH_SIDE_GPIO_02 GPIO_NUM_17
#define HIGH_SIDE_GPIO_03 GPIO_NUM_18
#define HIGH_SIDE_GPIO_04 GPIO_NUM_13
#define HIGH_SIDE_GPIO_05 GPIO_NUM_14
#define HIGH_SIDE_GPIO_06 GPIO_NUM_12
#define HIGH_SIDE_GPIO_07 GPIO_NUM_21
#define HIGH_SIDE_GPIO_08 GPIO_NUM_10
#define HIGH_SIDE_GPIO_09 GPIO_NUM_8
#define HIGH_SIDE_GPIO_10 GPIO_NUM_9
#define HIGH_SIDE_GPIO_11 GPIO_NUM_15
#define HIGH_SIDE_GPIO_12 GPIO_NUM_16
#define HIGH_SIDE_GPIO_13 GPIO_NUM_6
#define HIGH_SIDE_GPIO_14 GPIO_NUM_7
#define HIGH_SIDE_GPIO_15 GPIO_NUM_11

// Buttons

#define BUTTON_0_GPIO GPIO_NUM_37